"""Runtime port protocols."""

from __future__ import annotations

from datetime import datetime
from typing import Callable, Mapping, Protocol, Sequence

from domain.market import DataRequest, Quote
from domain.orders import OrderIntent, OrderState
from domain.portfolio import BrokerSnapshot


QuoteSink = Callable[[Quote], None]


class Clock(Protocol):
    def now(self) -> datetime: ...


class MarketDataPort(Protocol):
    async def connect(self) -> None: ...
    async def warmup(self, requests: tuple[DataRequest, ...]) -> Mapping[str, Mapping[str, Sequence[float]]]: ...
    async def subscribe(self, symbols: tuple[str, ...], sink: QuoteSink) -> None: ...
    async def disconnect(self) -> None: ...


class BrokerPort(Protocol):
    async def snapshot(self) -> BrokerSnapshot: ...
    async def submit(self, order: OrderIntent) -> OrderState: ...
    async def get_order(self, order_id: str) -> OrderState | None: ...
    async def list_open_orders(self, symbols: tuple[str, ...]) -> Sequence[OrderState]: ...
    async def cancel_open_orders(self, symbols: tuple[str, ...]) -> None: ...
    async def close_positions(self, symbols: tuple[str, ...]) -> Sequence[OrderState]: ...


class EventSink(Protocol):
    def record(self, event_type: str, payload: Mapping[str, object]) -> None: ...


class StatusPort(Protocol):
    def write(self, payload: Mapping[str, object]) -> None: ...
